---
prometheus_version:                 2.0.0
prometheus_alertmanager_version:    0.9.1
prometheus_blackbox_exporter_version:   0.7.0

prometheus_rule_files:
  common_rules:
    src: conf/common_alert.rules.yml
    dest: common_alert.rules.yml
  ssl_rules:
    src: conf/ssl_expiry.rules.yml
    dest: ssl_expiry.rules.yml
  http_rules:
    src: conf/http_alert.rules.yml
    dest: http_alert.rules.yml
  nginx_vts_rules:
    src: conf/nginx_vts_alert.rules.yml
    dest: nginx_vts_alert.rules.yml
  hpraid_rules:
    src: conf/hpraid.rules.yml
    dest: hpraid.rules.yml
  mdadm_rules:
    src: conf/mdadm.rules.yml
    dest: mdadm.rules.yml

node_exporter_version: '0.15.0'
redis_exporter_version: '0.13'
postgres_exporter_version: '0.3.0'
mysqld_exporter_version: '0.10.0'
nginx_vts_exporter_version: '0.5'
hpraid_exporter_version: '0.0.3'
process_exporter_version: '0.1.0'

prometheus_exporters_dict:

  node_exporter:
    version: '{{node_exporter_version}}'
    url: 'https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz'

  redis_exporter:
    version: '{{redis_exporter_version}}'
    url: 'https://github.com/oliver006/redis_exporter/releases/download/v{{redis_exporter_version}}/redis_exporter-v{{redis_exporter_version}}.linux-amd64.tar.gz'
    binary_path: "{{ prometheus_install_path }}/redis_exporter-{{redis_exporter_version}}.{{ prometheus_platform_suffix }}/redis_exporter"
    subdir: no
    options: "-redis.alias={{ inventory_hostname }}"

  postgres_exporter:
    version: '{{postgres_exporter_version}}'
    binary_url: 'https://github.com/wrouesnel/postgres_exporter/releases/download/v{{postgres_exporter_version}}/postgres_exporter'
    datasource: "user=postgres host=/var/run/postgresql/ sslmode=disable"

  mysqld_exporter:
    version: '{{mysqld_exporter_version}}'
    url: 'https://github.com/prometheus/mysqld_exporter/releases/download/v{{mysqld_exporter_version}}/mysqld_exporter-{{mysqld_exporter_version}}.linux-amd64.tar.gz'
    options: '-config.my-cnf={{ prometheus_install_path }}/mysqld_exporter-{{mysqld_exporter_version}}.{{ prometheus_platform_suffix }}/my.cnf'

  nginx_vts_exporter:
    version: '{{nginx_vts_exporter_version}}'
    url: 'https://github.com/hnlq715/nginx-vts-exporter/archive/v{{nginx_vts_exporter_version}}.tar.gz'
    binary_path: "{{ prometheus_install_path }}/nginx_vts_exporter-{{nginx_vts_exporter_version}}.{{ prometheus_platform_suffix }}/nginx-vts-exporter-{{nginx_vts_exporter_version}}/bin/nginx-vts-exporter"
    options: "-nginx.scrape_uri=http://example.com/format/json"
    subdir: no

  hpraid_exporter:
    version: '{{hpraid_exporter_version}}'
    url: 'https://github.com/chromium58/hpraid_exporter/releases/download/v{{hpraid_exporter_version}}/hpraid_exporter-{{hpraid_exporter_version}}.linux-amd64.tar.gz'
    options: '-cmd=/sbin/hpssacli'
    sudo: "yes"

  process_exporter:
    version: '{{process_exporter_version}}'
    url: 'https://github.com/ncabatoff/process-exporter/releases/download/v{{process_exporter_version}}/process-exporter-{{process_exporter_version}}.linux-amd64.tar.gz'
    binary_path: "{{ prometheus_install_path }}/process-exporter-{{process_exporter_version}}.{{ prometheus_platform_suffix }}/process-exporter"
    conf: yes
    options: "-config.path /etc/prometheus/process_exporter.yml"
    sudo: "yes"


prometheus_alertmanager_conf: "conf/alertmanager.yml"

prometheus_blackbox_conf: "conf/blackbox.yml"

prometheus_conf_main: "library/templates/prometheus.yml"

prometheus_alertmanager_url: "localhost:9093"

prometheus_postgres_datasource_variable: "user=postgres host=/var/run/postgresql/ sslmode=disable"

prometheus_allowed_ips:
  - "192.168.0.0/16"
  - "127.0.0.1/8"
